name: Deploy to Storefrontcloud
on:
  push:
    branches:
      - next
      - release/next
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/next'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: https://registry.npmjs.org/
      - name: Build packages
        run: |
          yarn
          yarn build:core
          yarn build:ct
          yarn build:prismic
          yarn build:checkout-com
      - name: Publish canary version
